# Generated by Django 4.1.3 on 2022-11-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_watering_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='watered',
            field=models.CharField(choices=[('T', 'Watered'), ('F', 'Not Watered')], default='T', max_length=1),
        ),
    ]
